#!/bin/bash
# Setup git post-merge hook for auto-updating embeddings
# This script installs a git hook that triggers incremental embedding updates
# after git pull or git merge operations

set -e

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${BLUE}🔧 Setting up auto-update hook for embeddings...${NC}"

# Find git root
GIT_ROOT=$(git rev-parse --show-toplevel 2>/dev/null)
if [ -z "$GIT_ROOT" ]; then
    echo "❌ Error: Not in a git repository"
    exit 1
fi

echo -e "${GREEN}✓${NC} Git root: $GIT_ROOT"

# Hook paths
HOOK_DIR="$GIT_ROOT/.git/hooks"
HOOK_FILE="$HOOK_DIR/post-merge"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PIPELINE_SCRIPT="$SCRIPT_DIR/embedding_pipeline.py"

# Check if pipeline exists
if [ ! -f "$PIPELINE_SCRIPT" ]; then
    echo "❌ Error: embedding_pipeline.py not found at $PIPELINE_SCRIPT"
    exit 1
fi

echo -e "${GREEN}✓${NC} Found embedding_pipeline.py"

# Create hooks directory if it doesn't exist
mkdir -p "$HOOK_DIR"

# Create post-merge hook
cat > "$HOOK_FILE" << 'HOOK_EOF'
#!/bin/bash
# Auto-update embeddings after git pull/merge
# Generated by setup_auto_update_hook.sh

# Only run if knowledge files changed
CHANGED_FILES=$(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD)

# Check if any .md files in agentes/ changed
if echo "$CHANGED_FILES" | grep -q "codexa.app/agentes/.*\.md$"; then
    echo "📚 Knowledge files changed, updating embeddings..."

    # Get script directory
    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)/codexa.app/agentes/mentor_agent/scripts"
    PIPELINE_SCRIPT="$SCRIPT_DIR/embedding_pipeline.py"

    if [ -f "$PIPELINE_SCRIPT" ]; then
        # Run incremental update in background
        python "$PIPELINE_SCRIPT" --update > /dev/null 2>&1 &
        echo "✅ Embedding update started in background"
    else
        echo "⚠️  Warning: embedding_pipeline.py not found, skipping update"
    fi
else
    echo "ℹ️  No knowledge files changed, skipping embedding update"
fi
HOOK_EOF

# Make hook executable
chmod +x "$HOOK_FILE"

echo -e "${GREEN}✓${NC} Post-merge hook created at: $HOOK_FILE"

# Create post-commit hook for optional use
POST_COMMIT_HOOK="$HOOK_DIR/post-commit"
cat > "$POST_COMMIT_HOOK" << 'HOOK_EOF'
#!/bin/bash
# Optional: Auto-update embeddings after commits
# Disabled by default - uncomment to enable

# # Only run if knowledge files changed in last commit
# CHANGED_FILES=$(git diff-tree --no-commit-id --name-only -r HEAD)
#
# if echo "$CHANGED_FILES" | grep -q "codexa.app/agentes/.*\.md$"; then
#     echo "📚 Knowledge files committed, updating embeddings..."
#
#     SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)/codexa.app/agentes/mentor_agent/scripts"
#     PIPELINE_SCRIPT="$SCRIPT_DIR/embedding_pipeline.py"
#
#     if [ -f "$PIPELINE_SCRIPT" ]; then
#         python "$PIPELINE_SCRIPT" --update > /dev/null 2>&1 &
#         echo "✅ Embedding update started in background"
#     fi
# fi
HOOK_EOF

chmod +x "$POST_COMMIT_HOOK"

echo -e "${GREEN}✓${NC} Post-commit hook created (disabled) at: $POST_COMMIT_HOOK"

echo ""
echo -e "${BLUE}✨ Setup complete!${NC}"
echo ""
echo "The following hooks have been installed:"
echo "  • post-merge:  Auto-update after git pull/merge (ENABLED)"
echo "  • post-commit: Auto-update after git commit (DISABLED)"
echo ""
echo "To enable post-commit hook, edit: $POST_COMMIT_HOOK"
echo "and uncomment the script content."
echo ""
echo -e "${YELLOW}Note:${NC} Make sure to install Python dependencies first:"
echo "  pip install -r $SCRIPT_DIR/requirements.txt"
echo ""
