"""
Example Usage: Google Imagen API Integration

This file shows practical examples of using the photo_agent
API integration to generate professional product photos.

Requirements:
1. Google API key configured in codexa.app/.env
2. Product image file (PNG/JPG)
3. Python 3.7+

Run examples:
    python EXAMPLE_USAGE.py --example 1
    python EXAMPLE_USAGE.py --example 2
    python EXAMPLE_USAGE.py --all
"""

import sys
from pathlib import Path

# Add codexa.app to path
AGENT_DIR = Path(__file__).parent
CODEXA_APP = AGENT_DIR.parent
sys.path.insert(0, str(CODEXA_APP))

from api_integrations import (
    generate_image_with_prompt,
    generate_batch_images,
    ImageGenerationResult,
)
from config.secrets import validate_api_keys


def check_setup():
    """Verify API key is configured before running examples."""
    print("=" * 70)
    print("Checking setup...")
    print("=" * 70)

    status = validate_api_keys()

    if not status['google_api_key']:
        print("❌ Google API key not configured!")
        print()
        print("Setup instructions:")
        print("1. cd codexa.app")
        print("2. cp .env.example .env")
        print("3. Edit .env and add your API key")
        print("4. Get key at: https://aistudio.google.com/app/apikey")
        print()
        return False

    print("✅ API key configured")
    print("✅ Ready to generate images")
    print()
    return True


def example_1_single_image():
    """
    Example 1: Generate a single marketplace photo

    Use case: Main product photo for Mercado Livre/Shopee
    - White background
    - Professional lighting
    - Centered composition
    """
    print("=" * 70)
    print("Example 1: Single Marketplace Photo")
    print("=" * 70)
    print()

    # Prompt (generated by photo_agent or custom)
    prompt = (
        "Professional product photography, pure white background (#FFFFFF), "
        "centered composition, soft even lighting, product fills 85% of frame, "
        "sharp focus, high detail, 8K resolution, no text, no watermarks, "
        "no logos, commercial photography style"
    )

    print("Prompt:")
    print(f"  {prompt}")
    print()

    # Note: Replace with your actual product image path
    reference_image = "path/to/your/product.jpg"
    output_path = "outputs/example_1_marketplace.png"

    print(f"Reference image: {reference_image}")
    print(f"Output path: {output_path}")
    print()
    print("Generating...")

    # Generate image
    result = generate_image_with_prompt(
        prompt=prompt,
        reference_image_path=reference_image,
        output_path=output_path,
        aspect_ratio='square',
        model='gemini-2.5-flash-image',
    )

    # Check result
    if result.success:
        print("✅ SUCCESS!")
        print(f"   Image saved to: {result.output_path}")
        print(f"   File size: {len(result.image_data)} bytes")
    else:
        print("❌ FAILED")
        print(f"   Error: {result.error_message}")

    print()
    print("=" * 70)
    print()


def example_2_lifestyle_photo():
    """
    Example 2: Generate a lifestyle photo

    Use case: Instagram, Facebook Ads, product gallery
    - Natural context
    - Golden hour lighting
    - Emotional appeal
    """
    print("=" * 70)
    print("Example 2: Lifestyle Photo")
    print("=" * 70)
    print()

    prompt = (
        "Lifestyle product photography, wooden picnic table setting, "
        "outdoor natural environment, golden hour soft warm lighting, "
        "shallow depth of field (f/2.8), product in natural use context, "
        "bokeh background, warm color grading, inviting atmosphere, "
        "8K resolution, editorial style, professional composition"
    )

    print("Prompt:")
    print(f"  {prompt}")
    print()

    reference_image = "path/to/your/product.jpg"
    output_path = "outputs/example_2_lifestyle.png"

    print(f"Reference image: {reference_image}")
    print(f"Output path: {output_path}")
    print()
    print("Generating...")

    result = generate_image_with_prompt(
        prompt=prompt,
        reference_image_path=reference_image,
        output_path=output_path,
        aspect_ratio='landscape',  # 16:9 for Instagram feed
        model='gemini-2.5-flash-image',
    )

    if result.success:
        print("✅ SUCCESS!")
        print(f"   Image saved to: {result.output_path}")
    else:
        print("❌ FAILED")
        print(f"   Error: {result.error_message}")

    print()
    print("=" * 70)
    print()


def example_3_batch_generation():
    """
    Example 3: Generate 9 professional scenes (full workflow)

    Use case: Complete product photography set
    - 9 different scenes
    - Mix of marketplace + lifestyle
    - Consistent product across all
    """
    print("=" * 70)
    print("Example 3: Batch Generation (9 Scenes)")
    print("=" * 70)
    print()

    # 9 professional prompts (normally generated by photo_agent)
    prompts = [
        # Scene 1: Marketplace main photo
        "Professional product photography, pure white background (#FFFFFF), centered, soft lighting, 8K, no text",

        # Scene 2: Lifestyle outdoor
        "Lifestyle photo, outdoor picnic setting, golden hour, warm tones, natural context, 8K",

        # Scene 3: Detail shot
        "Close-up detail shot, macro photography, soft focus background, studio lighting, high detail, 8K",

        # Scene 4: Hand holding
        "Product in hand, lifestyle context, neutral background, natural gesture, soft lighting, 8K",

        # Scene 5: Dramatic lighting
        "Dramatic product photography, low-key lighting, dark background, rim light, moody atmosphere, 8K",

        # Scene 6: Flat lay
        "Flat lay composition, top-down view, minimalist styling, complementary props, soft shadows, 8K",

        # Scene 7: Action shot
        "Product in use, action context, dynamic composition, natural lighting, authentic moment, 8K",

        # Scene 8: Lifestyle indoor
        "Lifestyle indoor setting, modern minimal interior, natural window light, cozy atmosphere, 8K",

        # Scene 9: Marketplace secondary
        "Professional product photography, white background, angled view, studio lighting, 8K, no text",
    ]

    print(f"Generating {len(prompts)} images...")
    print()

    reference_image = "path/to/your/product.jpg"
    output_dir = "outputs/batch_example"

    print(f"Reference image: {reference_image}")
    print(f"Output directory: {output_dir}")
    print(f"Estimated time: {len(prompts) * 2} seconds")
    print()

    # Generate batch
    results = generate_batch_images(
        prompts=prompts,
        reference_image_path=reference_image,
        output_dir=output_dir,
        aspect_ratio='square',
        model='gemini-2.5-flash-image',
        delay_between_requests=1.0,
    )

    # Analyze results
    successful = [r for r in results if r.success]
    failed = [r for r in results if not r.success]

    print()
    print("=" * 70)
    print("Results:")
    print("=" * 70)
    print(f"Total: {len(prompts)}")
    print(f"Successful: {len(successful)}")
    print(f"Failed: {len(failed)}")
    print(f"Success rate: {len(successful)/len(prompts)*100:.1f}%")
    print()

    if successful:
        print("✅ Successful images:")
        for i, result in enumerate(successful, 1):
            filename = Path(result.output_path).name
            print(f"   {i}. {filename}")
        print()

    if failed:
        print("❌ Failed images:")
        for i, result in enumerate(failed, 1):
            print(f"   {i}. {result.error_message}")
        print()

    print("=" * 70)
    print()


def example_4_brand_colors():
    """
    Example 4: Generate with brand colors

    Use case: Brand-consistent product photography
    - Specific brand colors
    - Consistent mood/style
    - Brand archetype alignment
    """
    print("=" * 70)
    print("Example 4: Brand-Aligned Photo")
    print("=" * 70)
    print()

    # Brand colors
    brand_color_primary = "#2C5F2D"  # Forest green
    brand_color_secondary = "#F8F8F8"  # Off-white

    prompt = (
        f"Professional product photography, minimalist studio setting, "
        f"background gradient from {brand_color_primary} to {brand_color_secondary}, "
        f"brand colors: forest green, off-white, eco-friendly aesthetic, "
        f"clean modern composition, soft natural lighting, 8K resolution, "
        f"brand identity consistent, professional commercial photography"
    )

    print("Brand colors:")
    print(f"  Primary: {brand_color_primary} (forest green)")
    print(f"  Secondary: {brand_color_secondary} (off-white)")
    print()
    print("Prompt:")
    print(f"  {prompt}")
    print()

    reference_image = "path/to/your/product.jpg"
    output_path = "outputs/example_4_brand.png"

    print(f"Reference image: {reference_image}")
    print(f"Output path: {output_path}")
    print()
    print("Generating...")

    result = generate_image_with_prompt(
        prompt=prompt,
        reference_image_path=reference_image,
        output_path=output_path,
        aspect_ratio='square',
        model='gemini-2.5-flash-image',
    )

    if result.success:
        print("✅ SUCCESS!")
        print(f"   Image saved to: {result.output_path}")
        print("   Brand colors applied successfully")
    else:
        print("❌ FAILED")
        print(f"   Error: {result.error_message}")

    print()
    print("=" * 70)
    print()


def example_5_high_quality():
    """
    Example 5: High-quality generation with Pro model

    Use case: Final production images
    - Gemini 3 Pro (higher quality)
    - Multiple reference images support
    - 4K resolution
    """
    print("=" * 70)
    print("Example 5: High-Quality Generation (Pro Model)")
    print("=" * 70)
    print()

    prompt = (
        "Professional product photography, studio setting, "
        "dramatic three-point lighting setup, high-end commercial quality, "
        "magazine editorial style, perfect composition, razor-sharp focus, "
        "4K resolution, color graded, professional retouching quality"
    )

    print("Model: gemini-3-pro-image-preview (higher quality)")
    print()
    print("Prompt:")
    print(f"  {prompt}")
    print()

    reference_image = "path/to/your/product.jpg"
    output_path = "outputs/example_5_pro.png"

    print(f"Reference image: {reference_image}")
    print(f"Output path: {output_path}")
    print()
    print("Generating (may take longer than Flash model)...")

    result = generate_image_with_prompt(
        prompt=prompt,
        reference_image_path=reference_image,
        output_path=output_path,
        aspect_ratio='square',
        model='gemini-3-pro-image-preview',  # Pro model
    )

    if result.success:
        print("✅ SUCCESS!")
        print(f"   Image saved to: {result.output_path}")
        print(f"   File size: {len(result.image_data)} bytes")
        print("   Note: Pro model provides higher quality and detail")
    else:
        print("❌ FAILED")
        print(f"   Error: {result.error_message}")

    print()
    print("=" * 70)
    print()


def main():
    """Run examples based on command line arguments."""
    import argparse

    parser = argparse.ArgumentParser(
        description="Photo Agent API Integration Examples"
    )
    parser.add_argument(
        '--example',
        type=int,
        choices=[1, 2, 3, 4, 5],
        help='Run specific example (1-5)'
    )
    parser.add_argument(
        '--all',
        action='store_true',
        help='Run all examples'
    )

    args = parser.parse_args()

    # Check setup first
    if not check_setup():
        return

    # Run examples
    if args.all:
        print("Running all examples...")
        print()
        example_1_single_image()
        example_2_lifestyle_photo()
        example_3_batch_generation()
        example_4_brand_colors()
        example_5_high_quality()

    elif args.example == 1:
        example_1_single_image()

    elif args.example == 2:
        example_2_lifestyle_photo()

    elif args.example == 3:
        example_3_batch_generation()

    elif args.example == 4:
        example_4_brand_colors()

    elif args.example == 5:
        example_5_high_quality()

    else:
        print("Usage:")
        print("  python EXAMPLE_USAGE.py --example 1    # Run example 1")
        print("  python EXAMPLE_USAGE.py --all          # Run all examples")
        print()
        print("Available examples:")
        print("  1. Single marketplace photo (white background)")
        print("  2. Lifestyle photo (outdoor scene)")
        print("  3. Batch generation (9 scenes)")
        print("  4. Brand-aligned photo (custom colors)")
        print("  5. High-quality (Pro model)")
        print()


if __name__ == "__main__":
    main()
